### Приветствие
GET http://localhost:8080/calculator

### Получуть сумму чисел
GET http://localhost:8080/calculator/plus?num1=5&num2=5

### Получить разность чисел
GET http://localhost:8080/calculator/minus?num1=5&num2=5

### Получить произведение чисел
GET http://localhost:8080/calculator/multiply?num1=5&num2=5

### Получить частное чисел
GET http://localhost:8080/calculator/divide?num1=5&num2=0
